### ISSUE TITLE
Colocar link do deploy no About

### ISSUE THREAD

**Issue by bruno3du** [francopoffo/calculadora-simples#1]
Isso é básico mas pode aumentar e muito a chance de um visitante acessar seu projeto sem ter que "casar" dentro do readme. Não estou desconsiderando o valor de te-lo no readme, mas pontuando que cada mais lugares o link do deploy esteja melhor.

**Comment by francopoffo** [comment]
Obrigado pelo feedback Bruno! Adicionei o link.
